<a href="https://colab.research.google.com/github/edwardsnj/GlyBerta/blob/main/demonstration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import httpimport, os.path

!pip install -q transformers

with httpimport.github_repo("edwardsnj", "GlyBerta", ref="main"):
  import glyberta

IUPAC_sequences = "iupacseq.txt"
BASEURL = "https://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/2tZbwHlPjE/"
if not os.path.exists(IUPAC_sequences):
  !wget {BASEURL}{IUPAC_sequences}
!wc -l {IUPAC_sequences}
!head {IUPAC_sequences}

GlyBerta v1.0.8
19621 iupacseq.txt
Neu5Gc(?2-?)Neu5Gc(?2-?)Gal(?1-?)Glc(?1-
Gal(?1-4)GlcNAc(?1-?)[Gal(?1-4)GlcNAc(?1-2)]Man(?1-3)[Neu5Ac(?2-6)Gal(?1-4)GlcNAc(?1-2)Man(?1-6)]Man(?1-4)GlcNAc(?1-4)GlcNAc(?1-
Glc(b1-3)Glc(b1-3)Glc(b1-
Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc(b1-
Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc(b1-
GlcNAc(b1-2/4)Man(a1-3)[Man(a1-3/6)Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(?1-
Neu5Ac(a2-3/6)Gal(b1-4)GlcNAc(b1-2)Man(a1-3)[Gal(b1-3)Gal(b1-4)GlcNAc(b1-2)[Gal(b1-3)Gal(b1-4)GlcNAc(b1-4)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)[Fuc(a1-6)]GlcNAc(b1-
Galf(a1-2)Galf(a1-4)Gal(b1-
GalNAc(a1-3)[Fuc(a1-2)]Gal(b1-4)GlcNAc(b1-3)[Neu5Gc(a2-6)]GalNAc(a1-
Gal(b1-3)GalNAc(a1-

In [2]:
!rm -rf glyberta-model
glyberta.run(f"train --data {IUPAC_sequences} --epochs 20")

Random seed: 1191726399
Loaded 19621 sequences from iupacseq.txt
Train: 15697   Validation: 1962   Test: 1962
Vocabulary size: 126
Validation out-of-vocabulary rate: 2/38226 = 0.005%
Test out-of-vocabulary rate: 0/38712 = 0.000%
Model parameters: 3,291,774

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.decoder.weight', 'lm_head.decoder.bias'].

Retained best model from epoch 19.0 (validation loss 0.2625, checkpoint ./glyberta-model/checkpoint-9329).

=== Test-set evaluation ===
  loss            : 0.2720
  perplexity      : 1.3125
  masked accuracy : 91.0391%

Saved model, tokenizer, and test_metrics.json to ./glyberta-model

In [3]:
glyberta.run(f"evaluate --output_dir ./glyberta-model --data ./glyberta-model/validation.txt")

glyberta.run(f"evaluate --output_dir ./glyberta-model --data ./glyberta-model/test.txt")

Random seed: 3516474195

=== Test-set evaluation ===
  loss            : 0.2738
  perplexity      : 1.3149
  masked accuracy : 90.8948%
Random seed: 1071116598

=== Test-set evaluation ===
  loss            : 0.2550
  perplexity      : 1.2904
  masked accuracy : 91.7098%